#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE	0

// Poké Balls
#define ITEM_MASTER_BALL	(ITEM_NONE + 1)		// 255 (guaranteed)
#define ITEM_ULTRA_BALL		(ITEM_NONE + 2)		// 2
#define ITEM_GREAT_BALL		(ITEM_NONE + 3)		// 1.5
#define ITEM_POKE_BALL		(ITEM_NONE + 4)		// 1; necessary for obtaining Shedinja
#define ITEM_SAFARI_BALL	(ITEM_NONE + 5)		// 1.5
#define ITEM_NET_BALL		(ITEM_NONE + 6)		// 3.5 if Water or Bug; else 1
#define ITEM_DIVE_BALL		(ITEM_NONE + 7)		// 3.5 while surfing, fishing, diving; else 1
#define ITEM_NEST_BALL		(ITEM_NONE + 8)		// (((41 - Level) * 4096) / 10) / 4096, if below Lv.30; else 1
#define ITEM_REPEAT_BALL	(ITEM_NONE + 9)		// 3.5 if already registered; else 1
#define ITEM_TIMER_BALL		(ITEM_NONE + 10)	// min(1 + turns * (1229 / 4096), 4)
#define ITEM_LUXURY_BALL	(ITEM_NONE + 11)	// 1; any increase of friendship is boosted by 1
#define ITEM_PREMIER_BALL	(ITEM_NONE + 12)	// 1; receive 1 for each 10 Balls of any type bought at once
#define ITEM_DUSK_BALL		(ITEM_NONE + 13)	// 3.5 at night or in a cave; else 1
#define ITEM_HEAL_BALL		(ITEM_NONE + 14)	// 1; heals HP, PP and Status
#define ITEM_QUICK_BALL		(ITEM_NONE + 15)	// 5 on first turn; else 1
#define ITEM_CHERISH_BALL	(ITEM_NONE + 16)	// 1
#define ITEM_FAST_BALL		(ITEM_NONE + 17)	// 4 if base Speed of 100+; else 1
#define ITEM_LEVEL_BALL		(ITEM_NONE + 18)	// 8 if own Lv. at least x4, 4 if own Lv. at least x2, 2 if own Lv. is higher; else 1
#define ITEM_LURE_BALL		(ITEM_NONE + 19)	// 5 if fishing; else 1
#define ITEM_HEAVY_BALL		(ITEM_NONE + 20)	// -20 if under 100.0kg, +0 if 100.0kg to 199.9kg, +20 if 200.0kg to 299.9kg, +30 if 300.0kg+ (applies to the Pokémon's catch rate which cannot be lower than 1.)
#define ITEM_LOVE_BALL		(ITEM_NONE + 21)	// 8 if same species but opposite gender; else 1
#define ITEM_FRIEND_BALL	(ITEM_NONE + 22)	// 1; sets friendship to 200
#define ITEM_MOON_BALL		(ITEM_NONE + 23)	// 4 if Pokémon evolves with Moon Stone; else 1
#define ITEM_SPORT_BALL		(ITEM_NONE + 24)	// 1.5
#define ITEM_DREAM_BALL		(ITEM_NONE + 25)	// 255 (guaranteed)

#define FIRST_BALL_INDEX	ITEM_MASTER_BALL
#define LAST_BALL_INDEX		ITEM_DREAM_BALL

// Medicine
#define ITEM_POTION			(LAST_BALL_INDEX + 1)
#define ITEM_SUPER_POTION	(LAST_BALL_INDEX + 2)
#define ITEM_HYPER_POTION	(LAST_BALL_INDEX + 3)
#define ITEM_MAX_POTION		(LAST_BALL_INDEX + 4)
#define ITEM_FULL_RESTORE	(LAST_BALL_INDEX + 5)
#define ITEM_REVIVE			(LAST_BALL_INDEX + 6)
#define ITEM_MAX_REVIVE		(LAST_BALL_INDEX + 7)
#define ITEM_FRESH_WATER	(LAST_BALL_INDEX + 8)
#define ITEM_SODA_POP		(LAST_BALL_INDEX + 9)
#define ITEM_LEMONADE		(LAST_BALL_INDEX + 10)
#define ITEM_MOOMOO_MILK	(LAST_BALL_INDEX + 11)
#define ITEM_ENERGY_POWDER	(LAST_BALL_INDEX + 12)
#define ITEM_ENERGY_ROOT	(LAST_BALL_INDEX + 13)
#define ITEM_HEAL_POWDER	(LAST_BALL_INDEX + 14)
#define ITEM_REVIVAL_HERB	(LAST_BALL_INDEX + 15)
#define ITEM_ANTIDOTE		(LAST_BALL_INDEX + 16)
#define ITEM_PARALYZE_HEAL	(LAST_BALL_INDEX + 17)
#define ITEM_BURN_HEAL		(LAST_BALL_INDEX + 18)
#define ITEM_ICE_HEAL		(LAST_BALL_INDEX + 19)
#define ITEM_AWAKENING		(LAST_BALL_INDEX + 20)
#define ITEM_FULL_HEAL		(LAST_BALL_INDEX + 21)
#define ITEM_ETHER			(LAST_BALL_INDEX + 22)
#define ITEM_MAX_ETHER		(LAST_BALL_INDEX + 23)
#define ITEM_ELIXIR			(LAST_BALL_INDEX + 24)
#define ITEM_MAX_ELIXIR		(LAST_BALL_INDEX + 25)
#define ITEM_BERRY_JUICE	(LAST_BALL_INDEX + 26)
#define ITEM_SACRED_ASH		(LAST_BALL_INDEX + 27)
#define ITEM_SWEET_HEART	(LAST_BALL_INDEX + 28)

#define FIRST_MEDICINE_INDEX	ITEM_POTION
#define LAST_MEDICINE_INDEX		ITEM_SWEET_HEART

// Regional Specialties
#define ITEM_RAGE_CANDY_BAR		(LAST_MEDICINE_INDEX + 1)
#define ITEM_LAVA_COOKIE		(LAST_MEDICINE_INDEX + 2)
#define ITEM_OLD_GATEAU			(LAST_MEDICINE_INDEX + 3)
#define ITEM_CASTELIACONE		(LAST_MEDICINE_INDEX + 4)
#define ITEM_LUMIOSE_GALETTE	(LAST_MEDICINE_INDEX + 5)
#define ITEM_SHALOUR_SABLE		(LAST_MEDICINE_INDEX + 6)

#define FIRST_SPECIALTY_INDEX	ITEM_RAGE_CANDY_BAR
#define LAST_SPECIALTY_INDEX	ITEM_SHALOUR_SABLE

// Vitamins
#define ITEM_HP_UP		(LAST_SPECIALTY_INDEX + 1)
#define ITEM_PROTEIN	(LAST_SPECIALTY_INDEX + 2)
#define ITEM_IRON		(LAST_SPECIALTY_INDEX + 3)
#define ITEM_CALCIUM	(LAST_SPECIALTY_INDEX + 4)
#define ITEM_ZINC		(LAST_SPECIALTY_INDEX + 5)
#define ITEM_CARBOS		(LAST_SPECIALTY_INDEX + 6)
#define ITEM_PP_UP		(LAST_SPECIALTY_INDEX + 7)
#define ITEM_PP_MAX		(LAST_SPECIALTY_INDEX + 8)

#define FIRST_VITAMIN_INDEX	ITEM_HP_UP
#define LAST_VITAMIN_INDEX	ITEM_PP_MAX

// EV Feathers
#define ITEM_HEALTH_FEATHER	(LAST_VITAMIN_INDEX + 1)
#define ITEM_MUSCLE_FEATHER	(LAST_VITAMIN_INDEX + 2)
#define ITEM_RESIST_FEATHER	(LAST_VITAMIN_INDEX + 3)
#define ITEM_GENIUS_FEATHER	(LAST_VITAMIN_INDEX + 4)
#define ITEM_CLEVER_FEATHER	(LAST_VITAMIN_INDEX + 5)
#define ITEM_SWIFT_FEATHER	(LAST_VITAMIN_INDEX + 6)

#define FIRST_EV_FEATHER_INDEX	ITEM_HEALTH_FEATHER
#define LAST_EV_FEATHER_INDEX	ITEM_SWIFT_FEATHER

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE	(LAST_EV_FEATHER_INDEX + 1)
#define ITEM_ABILITY_PATCH		(LAST_EV_FEATHER_INDEX + 2)

#define FIRST_ABILITY_ITEM_INDEX	ITEM_ABILITY_CAPSULE
#define LAST_ABILITY_ITEM_INDEX		ITEM_ABILITY_PATCH

// Mints
#define ITEM_LONELY_MINT	(LAST_ABILITY_ITEM_INDEX + 1)
#define ITEM_ADAMANT_MINT	(LAST_ABILITY_ITEM_INDEX + 2)
#define ITEM_NAUGHTY_MINT	(LAST_ABILITY_ITEM_INDEX + 3)
#define ITEM_BRAVE_MINT		(LAST_ABILITY_ITEM_INDEX + 4)
#define ITEM_BOLD_MINT		(LAST_ABILITY_ITEM_INDEX + 5)
#define ITEM_IMPISH_MINT	(LAST_ABILITY_ITEM_INDEX + 6)
#define ITEM_LAX_MINT		(LAST_ABILITY_ITEM_INDEX + 7)
#define ITEM_RELAXED_MINT	(LAST_ABILITY_ITEM_INDEX + 8)
#define ITEM_MODEST_MINT	(LAST_ABILITY_ITEM_INDEX + 9)
#define ITEM_MILD_MINT		(LAST_ABILITY_ITEM_INDEX + 10)
#define ITEM_RASH_MINT		(LAST_ABILITY_ITEM_INDEX + 11)
#define ITEM_QUIET_MINT		(LAST_ABILITY_ITEM_INDEX + 12)
#define ITEM_CALM_MINT		(LAST_ABILITY_ITEM_INDEX + 13)
#define ITEM_GENTLE_MINT	(LAST_ABILITY_ITEM_INDEX + 14)
#define ITEM_CAREFUL_MINT	(LAST_ABILITY_ITEM_INDEX + 15)
#define ITEM_SASSY_MINT		(LAST_ABILITY_ITEM_INDEX + 16)
#define ITEM_TIMID_MINT		(LAST_ABILITY_ITEM_INDEX + 17)
#define ITEM_HASTY_MINT		(LAST_ABILITY_ITEM_INDEX + 18)
#define ITEM_JOLLY_MINT		(LAST_ABILITY_ITEM_INDEX + 19)
#define ITEM_NAIVE_MINT		(LAST_ABILITY_ITEM_INDEX + 20)
#define ITEM_SERIOUS_MINT	(LAST_ABILITY_ITEM_INDEX + 21)

#define FIRST_MINT_INDEX	ITEM_LONELY_MINT
#define LAST_MINT_INDEX		ITEM_SERIOUS_MINT

// Candy
#define ITEM_RARE_CANDY	(LAST_MINT_INDEX + 1)

#define FIRST_CANDY_INDEX	ITEM_RARE_CANDY
#define LAST_CANDY_INDEX	ITEM_RARE_CANDY

// Medicinal Flutes
#define ITEM_BLUE_FLUTE		(LAST_CANDY_INDEX + 1)
#define ITEM_YELLOW_FLUTE	(LAST_CANDY_INDEX + 2)
#define ITEM_RED_FLUTE		(LAST_CANDY_INDEX + 3)

#define FIRST_MED_FLUTE_INDEX	ITEM_BLUE_FLUTE
#define LAST_MED_FLUTE_INDEX	ITEM_RED_FLUTE

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE	(LAST_MED_FLUTE_INDEX + 1)
#define ITEM_WHITE_FLUTE	(LAST_MED_FLUTE_INDEX + 2)

#define FIRST_ENC_FLUTE_INDEX	ITEM_BLACK_FLUTE
#define LAST_ENC_FLUTE_INDEX	ITEM_WHITE_FLUTE

// Encounter Modifiers
#define ITEM_REPEL			(LAST_ENC_FLUTE_INDEX + 1)
#define ITEM_SUPER_REPEL	(LAST_ENC_FLUTE_INDEX + 2)
#define ITEM_MAX_REPEL		(LAST_ENC_FLUTE_INDEX + 3)
#define ITEM_ESCAPE_ROPE	(LAST_ENC_FLUTE_INDEX + 4)

#define FIRST_ENCOUNTER_MOD_INDEX	ITEM_REPEL
#define LAST_ENCOUNTER_MOD_INDEX	ITEM_ESCAPE_ROPE

// X Items
#define ITEM_X_ATTACK		(LAST_ENCOUNTER_MOD_INDEX + 1)
#define ITEM_X_DEFENSE		(LAST_ENCOUNTER_MOD_INDEX + 2)
#define ITEM_X_SP_ATK		(LAST_ENCOUNTER_MOD_INDEX + 3)
#define ITEM_X_SP_DEF		(LAST_ENCOUNTER_MOD_INDEX + 4)
#define ITEM_X_SPEED		(LAST_ENCOUNTER_MOD_INDEX + 5)
#define ITEM_X_ACCURACY		(LAST_ENCOUNTER_MOD_INDEX + 6)
#define ITEM_DIRE_HIT		(LAST_ENCOUNTER_MOD_INDEX + 7)
#define ITEM_GUARD_SPEC		(LAST_ENCOUNTER_MOD_INDEX + 8)
#define ITEM_POKE_DOLL		(LAST_ENCOUNTER_MOD_INDEX + 9)
#define ITEM_FLUFFY_TAIL	(LAST_ENCOUNTER_MOD_INDEX + 10)
#define ITEM_POKE_TOY		(LAST_ENCOUNTER_MOD_INDEX + 11)

#define FIRST_X_ITEM_INDEX	ITEM_X_ATTACK
#define LAST_X_ITEM_INDEX	ITEM_POKE_TOY

// Treasures
#define ITEM_NUGGET				(LAST_X_ITEM_INDEX + 1)
#define ITEM_BIG_NUGGET			(LAST_X_ITEM_INDEX + 2)
#define ITEM_TINY_MUSHROOM		(LAST_X_ITEM_INDEX + 3)
#define ITEM_BIG_MUSHROOM		(LAST_X_ITEM_INDEX + 4)
#define ITEM_BALM_MUSHROOM		(LAST_X_ITEM_INDEX + 5)
#define ITEM_PEARL				(LAST_X_ITEM_INDEX + 6)
#define ITEM_BIG_PEARL			(LAST_X_ITEM_INDEX + 7)
#define ITEM_PEARL_STRING		(LAST_X_ITEM_INDEX + 8)
#define ITEM_STARDUST			(LAST_X_ITEM_INDEX + 9)
#define ITEM_STAR_PIECE			(LAST_X_ITEM_INDEX + 10)
#define ITEM_COMET_SHARD		(LAST_X_ITEM_INDEX + 11)
#define ITEM_SHOAL_SALT			(LAST_X_ITEM_INDEX + 12)
#define ITEM_SHOAL_SHELL		(LAST_X_ITEM_INDEX + 13)
#define ITEM_RED_SHARD			(LAST_X_ITEM_INDEX + 14)
#define ITEM_BLUE_SHARD			(LAST_X_ITEM_INDEX + 15)
#define ITEM_YELLOW_SHARD		(LAST_X_ITEM_INDEX + 16)
#define ITEM_GREEN_SHARD		(LAST_X_ITEM_INDEX + 17)
#define ITEM_HEART_SCALE		(LAST_X_ITEM_INDEX + 18)
#define ITEM_HONEY				(LAST_X_ITEM_INDEX + 19)
#define ITEM_RARE_BONE			(LAST_X_ITEM_INDEX + 20)
#define ITEM_ODD_KEYSTONE		(LAST_X_ITEM_INDEX + 21)
#define ITEM_PRETTY_FEATHER		(LAST_X_ITEM_INDEX + 22)
#define ITEM_RELIC_COPPER		(LAST_X_ITEM_INDEX + 23)
#define ITEM_RELIC_SILVER		(LAST_X_ITEM_INDEX + 24)
#define ITEM_RELIC_GOLD			(LAST_X_ITEM_INDEX + 25)
#define ITEM_RELIC_VASE			(LAST_X_ITEM_INDEX + 26)
#define ITEM_RELIC_BAND			(LAST_X_ITEM_INDEX + 27)
#define ITEM_RELIC_STATUE		(LAST_X_ITEM_INDEX + 28)
#define ITEM_RELIC_CROWN		(LAST_X_ITEM_INDEX + 29)
#define ITEM_STRANGE_SOUVENIR	(LAST_X_ITEM_INDEX + 30)

#define FIRST_TREASURE_INDEX	ITEM_NUGGET
#define LAST_TREASURE_INDEX		ITEM_STRANGE_SOUVENIR

// Fossils
#define ITEM_HELIX_FOSSIL	(LAST_TREASURE_INDEX + 1)
#define ITEM_DOME_FOSSIL	(LAST_TREASURE_INDEX + 2)
#define ITEM_OLD_AMBER		(LAST_TREASURE_INDEX + 3)
#define ITEM_ROOT_FOSSIL	(LAST_TREASURE_INDEX + 4)
#define ITEM_CLAW_FOSSIL	(LAST_TREASURE_INDEX + 5)
#define ITEM_ARMOR_FOSSIL	(LAST_TREASURE_INDEX + 6)
#define ITEM_SKULL_FOSSIL	(LAST_TREASURE_INDEX + 7)
#define ITEM_COVER_FOSSIL	(LAST_TREASURE_INDEX + 8)
#define ITEM_PLUME_FOSSIL	(LAST_TREASURE_INDEX + 9)
#define ITEM_JAW_FOSSIL		(LAST_TREASURE_INDEX + 10)
#define ITEM_SAIL_FOSSIL	(LAST_TREASURE_INDEX + 11)

#define FIRST_FOSSIL_INDEX	ITEM_HELIX_FOSSIL
#define LAST_FOSSIL_INDEX	ITEM_SAIL_FOSSIL

// Mulch
#define ITEM_GROWTH_MULCH	(LAST_FOSSIL_INDEX + 1)
#define ITEM_DAMP_MULCH		(LAST_FOSSIL_INDEX + 2)
#define ITEM_STABLE_MULCH	(LAST_FOSSIL_INDEX + 3)
#define ITEM_GOOEY_MULCH	(LAST_FOSSIL_INDEX + 4)
#define ITEM_RICH_MULCH		(LAST_FOSSIL_INDEX + 5)
#define ITEM_SURPRISE_MULCH	(LAST_FOSSIL_INDEX + 6)
#define ITEM_BOOST_MULCH	(LAST_FOSSIL_INDEX + 7)
#define ITEM_AMAZE_MULCH	(LAST_FOSSIL_INDEX + 8)

#define FIRST_MULCH_INDEX	ITEM_GROWTH_MULCH
#define LAST_MULCH_INDEX	ITEM_AMAZE_MULCH

// Apricorns
#define ITEM_RED_APRICORN		(LAST_MULCH_INDEX + 1)
#define ITEM_BLUE_APRICORN		(LAST_MULCH_INDEX + 2)
#define ITEM_YELLOW_APRICORN	(LAST_MULCH_INDEX + 3)
#define ITEM_GREEN_APRICORN		(LAST_MULCH_INDEX + 4)
#define ITEM_PINK_APRICORN		(LAST_MULCH_INDEX + 5)
#define ITEM_WHITE_APRICORN		(LAST_MULCH_INDEX + 6)
#define ITEM_BLACK_APRICORN		(LAST_MULCH_INDEX + 7)

#define FIRST_APRICORN_INDEX	ITEM_RED_APRICORN
#define LAST_APRICORN_INDEX		ITEM_BLACK_APRICORN

// Mail
#define ITEM_ORANGE_MAIL	(LAST_APRICORN_INDEX + 1)
#define ITEM_HARBOR_MAIL	(LAST_APRICORN_INDEX + 2)
#define ITEM_GLITTER_MAIL	(LAST_APRICORN_INDEX + 3)
#define ITEM_MECH_MAIL		(LAST_APRICORN_INDEX + 4)
#define ITEM_WOOD_MAIL		(LAST_APRICORN_INDEX + 5)
#define ITEM_WAVE_MAIL		(LAST_APRICORN_INDEX + 6)
#define ITEM_BEAD_MAIL		(LAST_APRICORN_INDEX + 7)
#define ITEM_SHADOW_MAIL	(LAST_APRICORN_INDEX + 8)
#define ITEM_TROPIC_MAIL	(LAST_APRICORN_INDEX + 9)
#define ITEM_DREAM_MAIL		(LAST_APRICORN_INDEX + 10)
#define ITEM_FAB_MAIL		(LAST_APRICORN_INDEX + 11)
#define ITEM_RETRO_MAIL		(LAST_APRICORN_INDEX + 12)

#define FIRST_MAIL_INDEX	ITEM_ORANGE_MAIL
#define LAST_MAIL_INDEX		ITEM_RETRO_MAIL

// Evolution Items
#define ITEM_FIRE_STONE		(LAST_MAIL_INDEX + 1)
#define ITEM_WATER_STONE	(LAST_MAIL_INDEX + 2)
#define ITEM_THUNDER_STONE	(LAST_MAIL_INDEX + 3)
#define ITEM_LEAF_STONE		(LAST_MAIL_INDEX + 4)
#define ITEM_ICE_STONE		(LAST_MAIL_INDEX + 5)
#define ITEM_SUN_STONE		(LAST_MAIL_INDEX + 6)
#define ITEM_MOON_STONE		(LAST_MAIL_INDEX + 7)
#define ITEM_SHINY_STONE	(LAST_MAIL_INDEX + 8)
#define ITEM_DUSK_STONE		(LAST_MAIL_INDEX + 9)
#define ITEM_DAWN_STONE		(LAST_MAIL_INDEX + 10)
#define ITEM_DRAGON_SCALE	(LAST_MAIL_INDEX + 11)
#define ITEM_UPGRADE		(LAST_MAIL_INDEX + 12)
#define ITEM_PROTECTOR		(LAST_MAIL_INDEX + 13)
#define ITEM_ELECTIRIZER	(LAST_MAIL_INDEX + 14)
#define ITEM_MAGMARIZER		(LAST_MAIL_INDEX + 15)
#define ITEM_DUBIOUS_DISC	(LAST_MAIL_INDEX + 16)
#define ITEM_REAPER_CLOTH	(LAST_MAIL_INDEX + 17)
#define ITEM_PRISM_SCALE	(LAST_MAIL_INDEX + 18)
#define ITEM_WHIPPED_DREAM	(LAST_MAIL_INDEX + 19)
#define ITEM_SACHET			(LAST_MAIL_INDEX + 20)
#define ITEM_OVAL_STONE		(LAST_MAIL_INDEX + 21)
#define ITEM_LINKING_CORD	(LAST_MAIL_INDEX + 22)
#define ITEM_EVERSTONE		(LAST_MAIL_INDEX + 23)

#define FIRST_EVO_ITEM_INDEX	ITEM_FIRE_STONE
#define LAST_EVO_ITEM_INDEX		ITEM_EVERSTONE

// Plates
#define ITEM_FLAME_PLATE	(LAST_EVO_ITEM_INDEX + 1)
#define ITEM_SPLASH_PLATE	(LAST_EVO_ITEM_INDEX + 2)
#define ITEM_ZAP_PLATE		(LAST_EVO_ITEM_INDEX + 3)
#define ITEM_MEADOW_PLATE	(LAST_EVO_ITEM_INDEX + 4)
#define ITEM_ICICLE_PLATE	(LAST_EVO_ITEM_INDEX + 5)
#define ITEM_FIST_PLATE		(LAST_EVO_ITEM_INDEX + 6)
#define ITEM_TOXIC_PLATE	(LAST_EVO_ITEM_INDEX + 7)
#define ITEM_EARTH_PLATE	(LAST_EVO_ITEM_INDEX + 8)
#define ITEM_SKY_PLATE		(LAST_EVO_ITEM_INDEX + 9)
#define ITEM_MIND_PLATE		(LAST_EVO_ITEM_INDEX + 10)
#define ITEM_INSECT_PLATE	(LAST_EVO_ITEM_INDEX + 11)
#define ITEM_STONE_PLATE	(LAST_EVO_ITEM_INDEX + 12)
#define ITEM_SPOOKY_PLATE	(LAST_EVO_ITEM_INDEX + 13)
#define ITEM_DRACO_PLATE	(LAST_EVO_ITEM_INDEX + 14)
#define ITEM_DREAD_PLATE	(LAST_EVO_ITEM_INDEX + 15)
#define ITEM_IRON_PLATE		(LAST_EVO_ITEM_INDEX + 16)
#define ITEM_PIXIE_PLATE	(LAST_EVO_ITEM_INDEX + 17)

#define FIRST_PLATE_INDEX	ITEM_FLAME_PLATE
#define LAST_PLATE_INDEX	ITEM_PIXIE_PLATE

// Drives
#define ITEM_DOUSE_DRIVE	(LAST_PLATE_INDEX + 1)
#define ITEM_SHOCK_DRIVE	(LAST_PLATE_INDEX + 2)
#define ITEM_BURN_DRIVE		(LAST_PLATE_INDEX + 3)
#define ITEM_CHILL_DRIVE	(LAST_PLATE_INDEX + 4)

#define FIRST_DRIVE_INDEX	ITEM_DOUSE_DRIVE
#define LAST_DRIVE_INDEX	ITEM_CHILL_DRIVE

// Colored Orbs
#define ITEM_RED_ORB	(LAST_DRIVE_INDEX + 1)
#define ITEM_BLUE_ORB	(LAST_DRIVE_INDEX + 2)

#define FIRST_ORB_INDEX	ITEM_RED_ORB
#define LAST_ORB_INDEX	ITEM_BLUE_ORB

// Mega Stones
#define ITEM_VENUSAURITE	(LAST_ORB_INDEX + 1)
#define ITEM_CHARIZARDITE_X	(LAST_ORB_INDEX + 2)
#define ITEM_CHARIZARDITE_Y	(LAST_ORB_INDEX + 3)
#define ITEM_BLASTOISINITE	(LAST_ORB_INDEX + 4)
#define ITEM_BEEDRILLITE	(LAST_ORB_INDEX + 5)
#define ITEM_PIDGEOTITE		(LAST_ORB_INDEX + 6)
#define ITEM_ALAKAZITE		(LAST_ORB_INDEX + 7)
#define ITEM_SLOWBRONITE	(LAST_ORB_INDEX + 8)
#define ITEM_GENGARITE		(LAST_ORB_INDEX + 9)
#define ITEM_KANGASKHANITE	(LAST_ORB_INDEX + 10)
#define ITEM_PINSIRITE		(LAST_ORB_INDEX + 11)
#define ITEM_GYARADOSITE	(LAST_ORB_INDEX + 12)
#define ITEM_AERODACTYLITE	(LAST_ORB_INDEX + 13)
#define ITEM_MEWTWONITE_X	(LAST_ORB_INDEX + 14)
#define ITEM_MEWTWONITE_Y	(LAST_ORB_INDEX + 15)
#define ITEM_AMPHAROSITE	(LAST_ORB_INDEX + 16)
#define ITEM_STEELIXITE		(LAST_ORB_INDEX + 17)
#define ITEM_SCIZORITE		(LAST_ORB_INDEX + 18)
#define ITEM_HERACRONITE	(LAST_ORB_INDEX + 19)
#define ITEM_HOUNDOOMINITE	(LAST_ORB_INDEX + 20)
#define ITEM_TYRANITARITE	(LAST_ORB_INDEX + 21)
#define ITEM_SCEPTILITE		(LAST_ORB_INDEX + 22)
#define ITEM_BLAZIKENITE	(LAST_ORB_INDEX + 23)
#define ITEM_SWAMPERTITE	(LAST_ORB_INDEX + 24)
#define ITEM_GARDEVOIRITE	(LAST_ORB_INDEX + 25)
#define ITEM_SABLENITE		(LAST_ORB_INDEX + 26)
#define ITEM_MAWILITE		(LAST_ORB_INDEX + 27)
#define ITEM_AGGRONITE		(LAST_ORB_INDEX + 28)
#define ITEM_MEDICHAMITE	(LAST_ORB_INDEX + 29)
#define ITEM_MANECTITE		(LAST_ORB_INDEX + 30)
#define ITEM_SHARPEDONITE	(LAST_ORB_INDEX + 31)
#define ITEM_CAMERUPTITE	(LAST_ORB_INDEX + 32)
#define ITEM_ALTARIANITE	(LAST_ORB_INDEX + 33)
#define ITEM_BANETTITE		(LAST_ORB_INDEX + 34)
#define ITEM_ABSOLITE		(LAST_ORB_INDEX + 35)
#define ITEM_GLALITITE		(LAST_ORB_INDEX + 36)
#define ITEM_SALAMENCITE	(LAST_ORB_INDEX + 37)
#define ITEM_METAGROSSITE	(LAST_ORB_INDEX + 38)
#define ITEM_LATIASITE		(LAST_ORB_INDEX + 39)
#define ITEM_LATIOSITE		(LAST_ORB_INDEX + 40)
#define ITEM_LOPUNNITE		(LAST_ORB_INDEX + 41)
#define ITEM_GARCHOMPITE	(LAST_ORB_INDEX + 42)
#define ITEM_LUCARIONITE	(LAST_ORB_INDEX + 43)
#define ITEM_ABOMASITE		(LAST_ORB_INDEX + 44)
#define ITEM_GALLADITE		(LAST_ORB_INDEX + 45)
#define ITEM_AUDINITE		(LAST_ORB_INDEX + 46)
#define ITEM_DIANCITE		(LAST_ORB_INDEX + 47)

#define FIRST_MEGA_STONE_INDEX	ITEM_VENUSAURITE
#define LAST_MEGA_STONE_INDEX	ITEM_DIANCITE

// Gems
#define ITEM_NORMAL_GEM		(LAST_MEGA_STONE_INDEX + 1)
#define ITEM_FIRE_GEM		(LAST_MEGA_STONE_INDEX + 2)
#define ITEM_WATER_GEM		(LAST_MEGA_STONE_INDEX + 3)
#define ITEM_ELECTRIC_GEM	(LAST_MEGA_STONE_INDEX + 4)
#define ITEM_GRASS_GEM		(LAST_MEGA_STONE_INDEX + 5)
#define ITEM_ICE_GEM		(LAST_MEGA_STONE_INDEX + 6)
#define ITEM_FIGHTING_GEM	(LAST_MEGA_STONE_INDEX + 7)
#define ITEM_POISON_GEM		(LAST_MEGA_STONE_INDEX + 8)
#define ITEM_GROUND_GEM		(LAST_MEGA_STONE_INDEX + 9)
#define ITEM_FLYING_GEM		(LAST_MEGA_STONE_INDEX + 10)
#define ITEM_PSYCHIC_GEM	(LAST_MEGA_STONE_INDEX + 11)
#define ITEM_BUG_GEM		(LAST_MEGA_STONE_INDEX + 12)
#define ITEM_ROCK_GEM		(LAST_MEGA_STONE_INDEX + 13)
#define ITEM_GHOST_GEM		(LAST_MEGA_STONE_INDEX + 14)
#define ITEM_DRAGON_GEM		(LAST_MEGA_STONE_INDEX + 15)
#define ITEM_DARK_GEM		(LAST_MEGA_STONE_INDEX + 16)
#define ITEM_STEEL_GEM		(LAST_MEGA_STONE_INDEX + 17)
#define ITEM_FAIRY_GEM		(LAST_MEGA_STONE_INDEX + 18)

#define FIRST_GEM_INDEX	ITEM_NORMAL_GEM
#define LAST_GEM_INDEX	ITEM_FAIRY_GEM

// Species-specific Held Items
#define ITEM_LIGHT_BALL		(LAST_GEM_INDEX + 1)
#define ITEM_LEEK			(LAST_GEM_INDEX + 2)
#define ITEM_THICK_CLUB		(LAST_GEM_INDEX + 3)
#define ITEM_LUCKY_PUNCH	(LAST_GEM_INDEX + 4)
#define ITEM_METAL_POWDER	(LAST_GEM_INDEX + 5)
#define ITEM_QUICK_POWDER	(LAST_GEM_INDEX + 6)
#define ITEM_DEEP_SEA_SCALE	(LAST_GEM_INDEX + 7)
#define ITEM_DEEP_SEA_TOOTH	(LAST_GEM_INDEX + 8)
#define ITEM_SOUL_DEW		(LAST_GEM_INDEX + 9)
#define ITEM_ADAMANT_ORB	(LAST_GEM_INDEX + 10)
#define ITEM_LUSTROUS_ORB	(LAST_GEM_INDEX + 11)
#define ITEM_GRISEOUS_ORB	(LAST_GEM_INDEX + 12)

#define FIRST_SPECIES_ITEM_INDEX	ITEM_LIGHT_BALL
#define LAST_SPECIES_ITEM_INDEX		ITEM_GRISEOUS_ORB

// Incenses
#define ITEM_SEA_INCENSE	(LAST_SPECIES_ITEM_INDEX + 1)
#define ITEM_LAX_INCENSE	(LAST_SPECIES_ITEM_INDEX + 2)
#define ITEM_ODD_INCENSE	(LAST_SPECIES_ITEM_INDEX + 3)
#define ITEM_ROCK_INCENSE	(LAST_SPECIES_ITEM_INDEX + 4)
#define ITEM_FULL_INCENSE	(LAST_SPECIES_ITEM_INDEX + 5)
#define ITEM_WAVE_INCENSE	(LAST_SPECIES_ITEM_INDEX + 6)
#define ITEM_ROSE_INCENSE	(LAST_SPECIES_ITEM_INDEX + 7)
#define ITEM_LUCK_INCENSE	(LAST_SPECIES_ITEM_INDEX + 8)
#define ITEM_PURE_INCENSE	(LAST_SPECIES_ITEM_INDEX + 9)

#define FIRST_INCENSE_INDEX	ITEM_SEA_INCENSE
#define LAST_INCENSE_INDEX	ITEM_PURE_INCENSE

// Contest Scarves
#define ITEM_RED_SCARF		(LAST_INCENSE_INDEX + 1)
#define ITEM_BLUE_SCARF		(LAST_INCENSE_INDEX + 2)
#define ITEM_PINK_SCARF		(LAST_INCENSE_INDEX + 3)
#define ITEM_GREEN_SCARF	(LAST_INCENSE_INDEX + 4)
#define ITEM_YELLOW_SCARF	(LAST_INCENSE_INDEX + 5)

#define FIRST_CONTEST_SCARF_INDEX	ITEM_RED_SCARF
#define LAST_CONTEST_SCARF_INDEX	ITEM_YELLOW_SCARF

// EV Gain Modifiers
#define ITEM_MACHO_BRACE	(LAST_CONTEST_SCARF_INDEX + 1)
#define ITEM_POWER_WEIGHT	(LAST_CONTEST_SCARF_INDEX + 2)
#define ITEM_POWER_BRACER	(LAST_CONTEST_SCARF_INDEX + 3)
#define ITEM_POWER_BELT		(LAST_CONTEST_SCARF_INDEX + 4)
#define ITEM_POWER_LENS		(LAST_CONTEST_SCARF_INDEX + 5)
#define ITEM_POWER_BAND		(LAST_CONTEST_SCARF_INDEX + 6)
#define ITEM_POWER_ANKLET	(LAST_CONTEST_SCARF_INDEX + 7)

#define FIRST_POWER_ITEM_INDEX	ITEM_MACHO_BRACE
#define LAST_POWER_ITEM_INDEX	ITEM_POWER_ANKLET

// Type-boosting Held Items
#define ITEM_SILK_SCARF		(LAST_POWER_ITEM_INDEX + 1)
#define ITEM_CHARCOAL		(LAST_POWER_ITEM_INDEX + 2)
#define ITEM_MYSTIC_WATER	(LAST_POWER_ITEM_INDEX + 3)
#define ITEM_MAGNET			(LAST_POWER_ITEM_INDEX + 4)
#define ITEM_MIRACLE_SEED	(LAST_POWER_ITEM_INDEX + 5)
#define ITEM_NEVER_MELT_ICE	(LAST_POWER_ITEM_INDEX + 6)
#define ITEM_BLACK_BELT		(LAST_POWER_ITEM_INDEX + 7)
#define ITEM_POISON_BARB	(LAST_POWER_ITEM_INDEX + 8)
#define ITEM_SOFT_SAND		(LAST_POWER_ITEM_INDEX + 9)
#define ITEM_SHARP_BEAK		(LAST_POWER_ITEM_INDEX + 10)
#define ITEM_TWISTED_SPOON	(LAST_POWER_ITEM_INDEX + 11)
#define ITEM_SILVER_POWDER	(LAST_POWER_ITEM_INDEX + 12)
#define ITEM_HARD_STONE		(LAST_POWER_ITEM_INDEX + 13)
#define ITEM_SPELL_TAG		(LAST_POWER_ITEM_INDEX + 14)
#define ITEM_DRAGON_FANG	(LAST_POWER_ITEM_INDEX + 15)
#define ITEM_BLACK_GLASSES	(LAST_POWER_ITEM_INDEX + 16)
#define ITEM_METAL_COAT		(LAST_POWER_ITEM_INDEX + 17)

#define FIRST_TYPE_ITEM_INDEX	ITEM_SILK_SCARF
#define LAST_TYPE_ITEM_INDEX	ITEM_METAL_COAT

// Choice Items
#define ITEM_CHOICE_BAND	(LAST_TYPE_ITEM_INDEX + 1)
#define ITEM_CHOICE_SPECS	(LAST_TYPE_ITEM_INDEX + 2)
#define ITEM_CHOICE_SCARF	(LAST_TYPE_ITEM_INDEX + 3)

#define FIRST_CHOICE_ITEM_INDEX	ITEM_CHOICE_BAND
#define LAST_CHOICE_ITEM_INDEX	ITEM_CHOICE_SCARF

// Status Orbs
#define ITEM_FLAME_ORB	(LAST_CHOICE_ITEM_INDEX + 1)
#define ITEM_TOXIC_ORB	(LAST_CHOICE_ITEM_INDEX + 2)

#define FIRST_STATUS_ORB_INDEX	ITEM_FLAME_ORB
#define LAST_STATUS_ORB_INDEX	ITEM_TOXIC_ORB

// Weather Rocks
#define ITEM_DAMP_ROCK		(LAST_STATUS_ORB_INDEX + 1)
#define ITEM_HEAT_ROCK		(LAST_STATUS_ORB_INDEX + 2)
#define ITEM_SMOOTH_ROCK	(LAST_STATUS_ORB_INDEX + 3)
#define ITEM_ICY_ROCK		(LAST_STATUS_ORB_INDEX + 4)

#define FIRST_WEATHER_ROCK_INDEX	ITEM_DAMP_ROCK
#define LAST_WEATHER_ROCK_INDEX		ITEM_ICY_ROCK

// Type-activated Stat Modifiers
#define ITEM_ABSORB_BULB	(LAST_WEATHER_ROCK_INDEX + 1)
#define ITEM_CELL_BATTERY	(LAST_WEATHER_ROCK_INDEX + 2)
#define ITEM_LUMINOUS_MOSS	(LAST_WEATHER_ROCK_INDEX + 3)
#define ITEM_SNOWBALL		(LAST_WEATHER_ROCK_INDEX + 4)

#define FIRST_TYPE_STAT_MOD_INDEX	ITEM_ABSORB_BULB
#define LAST_TYPE_STAT_MOD_INDEX	ITEM_SNOWBALL

// Misc. Held Items
#define ITEM_BRIGHT_POWDER		(LAST_TYPE_STAT_MOD_INDEX + 1)
#define ITEM_WHITE_HERB			(LAST_TYPE_STAT_MOD_INDEX + 2)
#define ITEM_EXP_SHARE			(LAST_TYPE_STAT_MOD_INDEX + 3)
#define ITEM_QUICK_CLAW			(LAST_TYPE_STAT_MOD_INDEX + 4)
#define ITEM_SOOTHE_BELL		(LAST_TYPE_STAT_MOD_INDEX + 5)
#define ITEM_MENTAL_HERB		(LAST_TYPE_STAT_MOD_INDEX + 6)
#define ITEM_KINGS_ROCK			(LAST_TYPE_STAT_MOD_INDEX + 7)
#define ITEM_AMULET_COIN		(LAST_TYPE_STAT_MOD_INDEX + 8)
#define ITEM_CLEANSE_TAG		(LAST_TYPE_STAT_MOD_INDEX + 9)
#define ITEM_SMOKE_BALL			(LAST_TYPE_STAT_MOD_INDEX + 10)
#define ITEM_FOCUS_BAND			(LAST_TYPE_STAT_MOD_INDEX + 11)
#define ITEM_LUCKY_EGG			(LAST_TYPE_STAT_MOD_INDEX + 12)
#define ITEM_SCOPE_LENS			(LAST_TYPE_STAT_MOD_INDEX + 13)
#define ITEM_LEFTOVERS			(LAST_TYPE_STAT_MOD_INDEX + 14)
#define ITEM_SHELL_BELL			(LAST_TYPE_STAT_MOD_INDEX + 15)
#define ITEM_WIDE_LENS			(LAST_TYPE_STAT_MOD_INDEX + 16)
#define ITEM_MUSCLE_BAND		(LAST_TYPE_STAT_MOD_INDEX + 17)
#define ITEM_WISE_GLASSES		(LAST_TYPE_STAT_MOD_INDEX + 18)
#define ITEM_EXPERT_BELT		(LAST_TYPE_STAT_MOD_INDEX + 19)
#define ITEM_LIGHT_CLAY			(LAST_TYPE_STAT_MOD_INDEX + 20)
#define ITEM_LIFE_ORB			(LAST_TYPE_STAT_MOD_INDEX + 21)
#define ITEM_POWER_HERB			(LAST_TYPE_STAT_MOD_INDEX + 22)
#define ITEM_FOCUS_SASH			(LAST_TYPE_STAT_MOD_INDEX + 23)
#define ITEM_ZOOM_LENS			(LAST_TYPE_STAT_MOD_INDEX + 24)
#define ITEM_METRONOME			(LAST_TYPE_STAT_MOD_INDEX + 25)
#define ITEM_IRON_BALL			(LAST_TYPE_STAT_MOD_INDEX + 26)
#define ITEM_LAGGING_TAIL		(LAST_TYPE_STAT_MOD_INDEX + 27)
#define ITEM_DESTINY_KNOT		(LAST_TYPE_STAT_MOD_INDEX + 28)
#define ITEM_BLACK_SLUDGE		(LAST_TYPE_STAT_MOD_INDEX + 29)
#define ITEM_GRIP_CLAW			(LAST_TYPE_STAT_MOD_INDEX + 30)
#define ITEM_STICKY_BARB		(LAST_TYPE_STAT_MOD_INDEX + 31)
#define ITEM_SHED_SHELL			(LAST_TYPE_STAT_MOD_INDEX + 32)
#define ITEM_BIG_ROOT			(LAST_TYPE_STAT_MOD_INDEX + 33)
#define ITEM_RAZOR_CLAW			(LAST_TYPE_STAT_MOD_INDEX + 34)
#define ITEM_RAZOR_FANG			(LAST_TYPE_STAT_MOD_INDEX + 35)
#define ITEM_EVIOLITE			(LAST_TYPE_STAT_MOD_INDEX + 36)
#define ITEM_FLOAT_STONE		(LAST_TYPE_STAT_MOD_INDEX + 37)
#define ITEM_ROCKY_HELMET		(LAST_TYPE_STAT_MOD_INDEX + 38)
#define ITEM_AIR_BALLOON		(LAST_TYPE_STAT_MOD_INDEX + 39)
#define ITEM_RED_CARD			(LAST_TYPE_STAT_MOD_INDEX + 40)
#define ITEM_RING_TARGET		(LAST_TYPE_STAT_MOD_INDEX + 41)
#define ITEM_BINDING_BAND		(LAST_TYPE_STAT_MOD_INDEX + 42)
#define ITEM_EJECT_BUTTON		(LAST_TYPE_STAT_MOD_INDEX + 43)
#define ITEM_WEAKNESS_POLICY	(LAST_TYPE_STAT_MOD_INDEX + 44)
#define ITEM_ASSAULT_VEST		(LAST_TYPE_STAT_MOD_INDEX + 45)
#define ITEM_SAFETY_GOGGLES		(LAST_TYPE_STAT_MOD_INDEX + 46)

#define FIRST_MISC_HELD_INDEX	ITEM_BRIGHT_POWDER
#define LAST_MISC_HELD_INDEX	ITEM_SAFETY_GOGGLES

// Berries
#define ITEM_CHERI_BERRY	(LAST_MISC_HELD_INDEX + 1)
#define ITEM_CHESTO_BERRY	(LAST_MISC_HELD_INDEX + 2)
#define ITEM_PECHA_BERRY	(LAST_MISC_HELD_INDEX + 3)
#define ITEM_RAWST_BERRY	(LAST_MISC_HELD_INDEX + 4)
#define ITEM_ASPEAR_BERRY	(LAST_MISC_HELD_INDEX + 5)
#define ITEM_LEPPA_BERRY	(LAST_MISC_HELD_INDEX + 6)
#define ITEM_ORAN_BERRY		(LAST_MISC_HELD_INDEX + 7)
#define ITEM_PERSIM_BERRY	(LAST_MISC_HELD_INDEX + 8)
#define ITEM_LUM_BERRY		(LAST_MISC_HELD_INDEX + 9)
#define ITEM_SITRUS_BERRY	(LAST_MISC_HELD_INDEX + 10)
#define ITEM_FIGY_BERRY		(LAST_MISC_HELD_INDEX + 11)
#define ITEM_WIKI_BERRY		(LAST_MISC_HELD_INDEX + 12)
#define ITEM_MAGO_BERRY		(LAST_MISC_HELD_INDEX + 13)
#define ITEM_AGUAV_BERRY	(LAST_MISC_HELD_INDEX + 14)
#define ITEM_IAPAPA_BERRY	(LAST_MISC_HELD_INDEX + 15)
#define ITEM_RAZZ_BERRY		(LAST_MISC_HELD_INDEX + 16)
#define ITEM_BLUK_BERRY		(LAST_MISC_HELD_INDEX + 17)
#define ITEM_NANAB_BERRY	(LAST_MISC_HELD_INDEX + 18)
#define ITEM_WEPEAR_BERRY	(LAST_MISC_HELD_INDEX + 19)
#define ITEM_PINAP_BERRY	(LAST_MISC_HELD_INDEX + 20)
#define ITEM_POMEG_BERRY	(LAST_MISC_HELD_INDEX + 21)
#define ITEM_KELPSY_BERRY	(LAST_MISC_HELD_INDEX + 22)
#define ITEM_QUALOT_BERRY	(LAST_MISC_HELD_INDEX + 23)
#define ITEM_HONDEW_BERRY	(LAST_MISC_HELD_INDEX + 24)
#define ITEM_GREPA_BERRY	(LAST_MISC_HELD_INDEX + 25)
#define ITEM_TAMATO_BERRY	(LAST_MISC_HELD_INDEX + 26)
#define ITEM_CORNN_BERRY	(LAST_MISC_HELD_INDEX + 27)
#define ITEM_MAGOST_BERRY	(LAST_MISC_HELD_INDEX + 28)
#define ITEM_RABUTA_BERRY	(LAST_MISC_HELD_INDEX + 29)
#define ITEM_NOMEL_BERRY	(LAST_MISC_HELD_INDEX + 30)
#define ITEM_SPELON_BERRY	(LAST_MISC_HELD_INDEX + 31)
#define ITEM_PAMTRE_BERRY	(LAST_MISC_HELD_INDEX + 32)
#define ITEM_WATMEL_BERRY	(LAST_MISC_HELD_INDEX + 33)
#define ITEM_DURIN_BERRY	(LAST_MISC_HELD_INDEX + 34)
#define ITEM_BELUE_BERRY	(LAST_MISC_HELD_INDEX + 35)
#define ITEM_CHILAN_BERRY	(LAST_MISC_HELD_INDEX + 36)
#define ITEM_OCCA_BERRY		(LAST_MISC_HELD_INDEX + 37)
#define ITEM_PASSHO_BERRY	(LAST_MISC_HELD_INDEX + 38)
#define ITEM_WACAN_BERRY	(LAST_MISC_HELD_INDEX + 39)
#define ITEM_RINDO_BERRY	(LAST_MISC_HELD_INDEX + 40)
#define ITEM_YACHE_BERRY	(LAST_MISC_HELD_INDEX + 41)
#define ITEM_CHOPLE_BERRY	(LAST_MISC_HELD_INDEX + 42)
#define ITEM_KEBIA_BERRY	(LAST_MISC_HELD_INDEX + 43)
#define ITEM_SHUCA_BERRY	(LAST_MISC_HELD_INDEX + 44)
#define ITEM_COBA_BERRY		(LAST_MISC_HELD_INDEX + 45)
#define ITEM_PAYAPA_BERRY	(LAST_MISC_HELD_INDEX + 46)
#define ITEM_TANGA_BERRY	(LAST_MISC_HELD_INDEX + 47)
#define ITEM_CHARTI_BERRY	(LAST_MISC_HELD_INDEX + 48)
#define ITEM_KASIB_BERRY	(LAST_MISC_HELD_INDEX + 49)
#define ITEM_HABAN_BERRY	(LAST_MISC_HELD_INDEX + 50)
#define ITEM_COLBUR_BERRY	(LAST_MISC_HELD_INDEX + 51)
#define ITEM_BABIRI_BERRY	(LAST_MISC_HELD_INDEX + 52)
#define ITEM_ROSELI_BERRY	(LAST_MISC_HELD_INDEX + 53)
#define ITEM_LIECHI_BERRY	(LAST_MISC_HELD_INDEX + 54)
#define ITEM_GANLON_BERRY	(LAST_MISC_HELD_INDEX + 55)
#define ITEM_SALAC_BERRY	(LAST_MISC_HELD_INDEX + 56)
#define ITEM_PETAYA_BERRY	(LAST_MISC_HELD_INDEX + 57)
#define ITEM_APICOT_BERRY	(LAST_MISC_HELD_INDEX + 58)
#define ITEM_LANSAT_BERRY	(LAST_MISC_HELD_INDEX + 59)
#define ITEM_STARF_BERRY	(LAST_MISC_HELD_INDEX + 60)
#define ITEM_ENIGMA_BERRY	(LAST_MISC_HELD_INDEX + 61)
#define ITEM_MICLE_BERRY	(LAST_MISC_HELD_INDEX + 62)
#define ITEM_CUSTAP_BERRY	(LAST_MISC_HELD_INDEX + 63)
#define ITEM_JABOCA_BERRY	(LAST_MISC_HELD_INDEX + 64)
#define ITEM_ROWAP_BERRY	(LAST_MISC_HELD_INDEX + 65)
#define ITEM_KEE_BERRY		(LAST_MISC_HELD_INDEX + 66)
#define ITEM_MARANGA_BERRY	(LAST_MISC_HELD_INDEX + 67)
#define ITEM_ENIGMA_BERRY_E_READER	(LAST_MISC_HELD_INDEX + 68)

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define ITEM_TM01	(LAST_BERRY_INDEX + 1)
#define ITEM_TM02	(LAST_BERRY_INDEX + 2)
#define ITEM_TM03	(LAST_BERRY_INDEX + 3)
#define ITEM_TM04	(LAST_BERRY_INDEX + 4)
#define ITEM_TM05	(LAST_BERRY_INDEX + 5)
#define ITEM_TM06	(LAST_BERRY_INDEX + 6)
#define ITEM_TM07	(LAST_BERRY_INDEX + 7)
#define ITEM_TM08	(LAST_BERRY_INDEX + 8)
#define ITEM_TM09	(LAST_BERRY_INDEX + 9)
#define ITEM_TM10	(LAST_BERRY_INDEX + 10)
#define ITEM_TM11	(LAST_BERRY_INDEX + 11)
#define ITEM_TM12	(LAST_BERRY_INDEX + 12)
#define ITEM_TM13	(LAST_BERRY_INDEX + 13)
#define ITEM_TM14	(LAST_BERRY_INDEX + 14)
#define ITEM_TM15	(LAST_BERRY_INDEX + 15)
#define ITEM_TM16	(LAST_BERRY_INDEX + 16)
#define ITEM_TM17	(LAST_BERRY_INDEX + 17)
#define ITEM_TM18	(LAST_BERRY_INDEX + 18)
#define ITEM_TM19	(LAST_BERRY_INDEX + 19)
#define ITEM_TM20	(LAST_BERRY_INDEX + 20)
#define ITEM_TM21	(LAST_BERRY_INDEX + 21)
#define ITEM_TM22	(LAST_BERRY_INDEX + 22)
#define ITEM_TM23	(LAST_BERRY_INDEX + 23)
#define ITEM_TM24	(LAST_BERRY_INDEX + 24)
#define ITEM_TM25	(LAST_BERRY_INDEX + 25)
#define ITEM_TM26	(LAST_BERRY_INDEX + 26)
#define ITEM_TM27	(LAST_BERRY_INDEX + 27)
#define ITEM_TM28	(LAST_BERRY_INDEX + 28)
#define ITEM_TM29	(LAST_BERRY_INDEX + 29)
#define ITEM_TM30	(LAST_BERRY_INDEX + 30)
#define ITEM_TM31	(LAST_BERRY_INDEX + 31)
#define ITEM_TM32	(LAST_BERRY_INDEX + 32)
#define ITEM_TM33	(LAST_BERRY_INDEX + 33)
#define ITEM_TM34	(LAST_BERRY_INDEX + 34)
#define ITEM_TM35	(LAST_BERRY_INDEX + 35)
#define ITEM_TM36	(LAST_BERRY_INDEX + 36)
#define ITEM_TM37	(LAST_BERRY_INDEX + 37)
#define ITEM_TM38	(LAST_BERRY_INDEX + 38)
#define ITEM_TM39	(LAST_BERRY_INDEX + 39)
#define ITEM_TM40	(LAST_BERRY_INDEX + 40)
#define ITEM_TM41	(LAST_BERRY_INDEX + 41)
#define ITEM_TM42	(LAST_BERRY_INDEX + 42)
#define ITEM_TM43	(LAST_BERRY_INDEX + 43)
#define ITEM_TM44	(LAST_BERRY_INDEX + 44)
#define ITEM_TM45	(LAST_BERRY_INDEX + 45)
#define ITEM_TM46	(LAST_BERRY_INDEX + 46)
#define ITEM_TM47	(LAST_BERRY_INDEX + 47)
#define ITEM_TM48	(LAST_BERRY_INDEX + 48)
#define ITEM_TM49	(LAST_BERRY_INDEX + 49)
#define ITEM_TM50	(LAST_BERRY_INDEX + 50)
#define ITEM_TM51	(LAST_BERRY_INDEX + 51)
#define ITEM_TM52	(LAST_BERRY_INDEX + 52)
#define ITEM_TM53	(LAST_BERRY_INDEX + 53)
#define ITEM_TM54	(LAST_BERRY_INDEX + 54)
#define ITEM_TM55	(LAST_BERRY_INDEX + 55)
#define ITEM_TM56	(LAST_BERRY_INDEX + 56)
#define ITEM_TM57	(LAST_BERRY_INDEX + 57)
#define ITEM_TM58	(LAST_BERRY_INDEX + 58)
#define ITEM_TM59	(LAST_BERRY_INDEX + 59)
#define ITEM_TM60	(LAST_BERRY_INDEX + 60)
#define ITEM_TM61	(LAST_BERRY_INDEX + 61)
#define ITEM_TM62	(LAST_BERRY_INDEX + 62)
#define ITEM_TM63	(LAST_BERRY_INDEX + 63)
#define ITEM_TM64	(LAST_BERRY_INDEX + 64)
#define ITEM_TM65	(LAST_BERRY_INDEX + 65)
#define ITEM_TM66	(LAST_BERRY_INDEX + 66)
#define ITEM_TM67	(LAST_BERRY_INDEX + 67)
#define ITEM_TM68	(LAST_BERRY_INDEX + 68)
#define ITEM_TM69	(LAST_BERRY_INDEX + 69)
#define ITEM_TM70	(LAST_BERRY_INDEX + 70)
#define ITEM_TM71	(LAST_BERRY_INDEX + 71)
#define ITEM_TM72	(LAST_BERRY_INDEX + 72)
#define ITEM_TM73	(LAST_BERRY_INDEX + 73)
#define ITEM_TM74	(LAST_BERRY_INDEX + 74)
#define ITEM_TM75	(LAST_BERRY_INDEX + 75)
#define ITEM_TM76	(LAST_BERRY_INDEX + 76)
#define ITEM_TM77	(LAST_BERRY_INDEX + 77)
#define ITEM_TM78	(LAST_BERRY_INDEX + 78)
#define ITEM_TM79	(LAST_BERRY_INDEX + 79)
#define ITEM_TM80	(LAST_BERRY_INDEX + 80)
#define ITEM_TM81	(LAST_BERRY_INDEX + 81)
#define ITEM_TM82	(LAST_BERRY_INDEX + 82)
#define ITEM_TM83	(LAST_BERRY_INDEX + 83)
#define ITEM_TM84	(LAST_BERRY_INDEX + 84)
#define ITEM_TM85	(LAST_BERRY_INDEX + 85)
#define ITEM_TM86	(LAST_BERRY_INDEX + 86)
#define ITEM_TM87	(LAST_BERRY_INDEX + 87)
#define ITEM_TM88	(LAST_BERRY_INDEX + 88)
#define ITEM_TM89	(LAST_BERRY_INDEX + 89)
#define ITEM_TM90	(LAST_BERRY_INDEX + 90)
#define ITEM_TM91	(LAST_BERRY_INDEX + 91)
#define ITEM_TM92	(LAST_BERRY_INDEX + 92)
#define ITEM_TM93	(LAST_BERRY_INDEX + 93)
#define ITEM_TM94	(LAST_BERRY_INDEX + 94)
#define ITEM_TM95	(LAST_BERRY_INDEX + 95)
#define ITEM_TM96	(LAST_BERRY_INDEX + 96)
#define ITEM_TM97	(LAST_BERRY_INDEX + 97)
#define ITEM_TM98	(LAST_BERRY_INDEX + 98)
#define ITEM_TM99	(LAST_BERRY_INDEX + 99)
#define ITEM_TM100	(LAST_BERRY_INDEX + 100)
#define ITEM_HM01	(LAST_BERRY_INDEX + 101)
#define ITEM_HM02	(LAST_BERRY_INDEX + 102)
#define ITEM_HM03	(LAST_BERRY_INDEX + 103)
#define ITEM_HM04	(LAST_BERRY_INDEX + 104)
#define ITEM_HM05	(LAST_BERRY_INDEX + 105)
#define ITEM_HM06	(LAST_BERRY_INDEX + 106)
#define ITEM_HM07	(LAST_BERRY_INDEX + 107)
#define ITEM_HM08	(LAST_BERRY_INDEX + 108)

#define ITEM_TM_HONE_CLAWS		ITEM_TM01
#define ITEM_TM_DRAGON_CLAW		ITEM_TM02
#define ITEM_TM_PSYSHOCK		ITEM_TM03
#define ITEM_TM_CALM_MIND		ITEM_TM04
#define ITEM_TM_ROAR			ITEM_TM05
#define ITEM_TM_TOXIC			ITEM_TM06
#define ITEM_TM_HAIL			ITEM_TM07
#define ITEM_TM_BULK_UP			ITEM_TM08
#define ITEM_TM_VENOSHOCK		ITEM_TM09
#define ITEM_TM_HIDDEN_POWER	ITEM_TM10
#define ITEM_TM_SUNNY_DAY		ITEM_TM11
#define ITEM_TM_TAUNT			ITEM_TM12
#define ITEM_TM_ICE_BEAM		ITEM_TM13
#define ITEM_TM_BLIZZARD		ITEM_TM14
#define ITEM_TM_HYPER_BEAM		ITEM_TM15
#define ITEM_TM_LIGHT_SCREEN	ITEM_TM16
#define ITEM_TM_PROTECT			ITEM_TM17
#define ITEM_TM_RAIN_DANCE		ITEM_TM18
#define ITEM_TM_ROOST			ITEM_TM19
#define ITEM_TM_SAFEGUARD		ITEM_TM20
#define ITEM_TM_FRUSTRATION		ITEM_TM21
#define ITEM_TM_SOLAR_BEAM		ITEM_TM22
#define ITEM_TM_SMACK_DOWN		ITEM_TM23
#define ITEM_TM_THUNDERBOLT		ITEM_TM24
#define ITEM_TM_THUNDER			ITEM_TM25
#define ITEM_TM_EARTHQUAKE		ITEM_TM26
#define ITEM_TM_RETURN			ITEM_TM27
#define ITEM_TM_DIG				ITEM_TM28
#define ITEM_TM_PSYCHIC			ITEM_TM29
#define ITEM_TM_SHADOW_BALL		ITEM_TM30
#define ITEM_TM_BRICK_BREAK		ITEM_TM31
#define ITEM_TM_DOUBLE_TEAM		ITEM_TM32
#define ITEM_TM_REFLECT			ITEM_TM33
#define ITEM_TM_SLUDGE_WAVE		ITEM_TM34
#define ITEM_TM_FLAMETHROWER	ITEM_TM35
#define ITEM_TM_SLUDGE_BOMB		ITEM_TM36
#define ITEM_TM_SANDSTORM		ITEM_TM37
#define ITEM_TM_FIRE_BLAST		ITEM_TM38
#define ITEM_TM_ROCK_TOMB		ITEM_TM39
#define ITEM_TM_AERIAL_ACE		ITEM_TM40
#define ITEM_TM_TORMENT			ITEM_TM41
#define ITEM_TM_FACADE			ITEM_TM42
#define ITEM_TM_FLAME_CHARGE	ITEM_TM43
#define ITEM_TM_REST			ITEM_TM44
#define ITEM_TM_ATTRACT			ITEM_TM45
#define ITEM_TM_THIEF			ITEM_TM46
#define ITEM_TM_LOW_SWEEP		ITEM_TM47
#define ITEM_TM_ROUND			ITEM_TM48
#define ITEM_TM_ECHOED_VOICE	ITEM_TM49
#define ITEM_TM_OVERHEAT		ITEM_TM50
#define ITEM_TM_STEEL_WING		ITEM_TM51
#define ITEM_TM_FOCUS_BLAST		ITEM_TM52
#define ITEM_TM_ENERGY_BALL		ITEM_TM53
#define ITEM_TM_FALSE_SWIPE		ITEM_TM54
#define ITEM_TM_SCALD			ITEM_TM55
#define ITEM_TM_FLING			ITEM_TM56
#define ITEM_TM_CHARGE_BEAM		ITEM_TM57
#define ITEM_TM_SKY_DROP		ITEM_TM58
#define ITEM_TM_INCINERATE		ITEM_TM59
#define ITEM_TM_QUASH			ITEM_TM60
#define ITEM_TM_WILL_O_WISP		ITEM_TM61
#define ITEM_TM_ACROBATICS		ITEM_TM62
#define ITEM_TM_EMBARGO			ITEM_TM63
#define ITEM_TM_TELEKINESIS		ITEM_TM64
#define ITEM_TM_SHADOW_CLAW		ITEM_TM65
#define ITEM_TM_PAYBACK			ITEM_TM66
#define ITEM_TM_RETALIATE		ITEM_TM67
#define ITEM_TM_GIGA_IMPACT		ITEM_TM68
#define ITEM_TM_ROCK_POLISH		ITEM_TM69
#define ITEM_TM_BRINE			ITEM_TM70
#define ITEM_TM_STONE_EDGE		ITEM_TM71
#define ITEM_TM_VOLT_SWITCH		ITEM_TM72
#define ITEM_TM_SILVER_WIND		ITEM_TM73
#define ITEM_TM_GYRO_BALL		ITEM_TM74
#define ITEM_TM_AVALANCHE		ITEM_TM75
#define ITEM_TM_STRUGGLE_BUG	ITEM_TM76
#define ITEM_TM_PSYCH_UP		ITEM_TM77
#define ITEM_TM_BULLDOZE		ITEM_TM78
#define ITEM_TM_FROST_BREATH	ITEM_TM79
#define ITEM_TM_CAPTIVATE		ITEM_TM80
#define ITEM_TM_X_SCISSOR		ITEM_TM81
#define ITEM_TM_DRAGON_TAIL		ITEM_TM82
#define ITEM_TM_INFESTATION		ITEM_TM83
#define ITEM_TM_POISON_JAB		ITEM_TM84
#define ITEM_TM_WORK_UP			ITEM_TM85
#define ITEM_TM_GRASS_KNOT		ITEM_TM86
#define ITEM_TM_SWAGGER			ITEM_TM87
#define ITEM_TM_SLEEP_TALK		ITEM_TM88
#define ITEM_TM_U_TURN			ITEM_TM89
#define ITEM_TM_PLUCK			ITEM_TM90
#define ITEM_TM_FLASH_CANNON	ITEM_TM91
#define ITEM_TM_TRICK_ROOM		ITEM_TM92
#define ITEM_TM_WILD_CHARGE		ITEM_TM93
#define ITEM_TM_SECRET_POWER	ITEM_TM94
#define ITEM_TM_SNARL			ITEM_TM95
#define ITEM_TM_NATURE_POWER	ITEM_TM96
#define ITEM_TM_DARK_PULSE		ITEM_TM97
#define ITEM_TM_POWER_UP_PUNCH	ITEM_TM98
#define ITEM_TM_DAZZLING_GLEAM	ITEM_TM99
#define ITEM_TM_CONFIDE			ITEM_TM100
#define ITEM_HM_CUT				ITEM_HM01
#define ITEM_HM_FLY				ITEM_HM02
#define ITEM_HM_SURF			ITEM_HM03
#define ITEM_HM_STRENGTH		ITEM_HM04
#define ITEM_HM_FLASH			ITEM_HM05
#define ITEM_HM_ROCK_SMASH		ITEM_HM06
#define ITEM_HM_WATERFALL		ITEM_HM07
#define ITEM_HM_DIVE			ITEM_HM08

#define FIRST_TMHM_INDEX	ITEM_TM01
#define LAST_TMHM_INDEX		ITEM_HM08

// Charms
#define ITEM_OVAL_CHARM		(LAST_TMHM_INDEX + 1)
#define ITEM_SHINY_CHARM	(LAST_TMHM_INDEX + 2)

#define FIRST_CHARM_INDEX	ITEM_OVAL_CHARM
#define LAST_CHARM_INDEX	ITEM_SHINY_CHARM

// Form-changing Key Items
#define ITEM_GRACIDEA		(LAST_CHARM_INDEX + 1)
#define ITEM_REVEAL_GLASS	(LAST_CHARM_INDEX + 2)
#define ITEM_DNA_SPLICERS	(LAST_CHARM_INDEX + 3)
#define ITEM_PRISON_BOTTLE	(LAST_CHARM_INDEX + 4)

#define FIRST_FORM_CHANGE_INDEX	ITEM_GRACIDEA
#define LAST_FORM_CHANGE_INDEX	ITEM_PRISON_BOTTLE

// Battle Mechanic Key Items
#define ITEM_MEGA_RING	(LAST_FORM_CHANGE_INDEX + 1)

#define FIRST_BATTLE_MECHANIC_INDEX	ITEM_MEGA_RING
#define LAST_BATTLE_MECHANIC_INDEX	ITEM_MEGA_RING

// Misc. Key Items
#define ITEM_BICYCLE		(LAST_BATTLE_MECHANIC_INDEX + 1)
#define ITEM_MACH_BIKE		(LAST_BATTLE_MECHANIC_INDEX + 2)
#define ITEM_ACRO_BIKE		(LAST_BATTLE_MECHANIC_INDEX + 3)
#define ITEM_OLD_ROD		(LAST_BATTLE_MECHANIC_INDEX + 4)
#define ITEM_GOOD_ROD		(LAST_BATTLE_MECHANIC_INDEX + 5)
#define ITEM_SUPER_ROD		(LAST_BATTLE_MECHANIC_INDEX + 6)
#define ITEM_ITEMFINDER		(LAST_BATTLE_MECHANIC_INDEX + 7)
#define ITEM_TOWN_MAP		(LAST_BATTLE_MECHANIC_INDEX + 8)
#define ITEM_VS_SEEKER		(LAST_BATTLE_MECHANIC_INDEX + 9)
#define ITEM_TM_CASE		(LAST_BATTLE_MECHANIC_INDEX + 10)
#define ITEM_BERRY_POUCH	(LAST_BATTLE_MECHANIC_INDEX + 11)
#define ITEM_COIN_CASE		(LAST_BATTLE_MECHANIC_INDEX + 12)
#define ITEM_POWDER_JAR		(LAST_BATTLE_MECHANIC_INDEX + 13)
#define ITEM_WAILMER_PAIL	(LAST_BATTLE_MECHANIC_INDEX + 14)
#define ITEM_POKE_RADAR		(LAST_BATTLE_MECHANIC_INDEX + 15)
#define ITEM_POKEBLOCK_CASE	(LAST_BATTLE_MECHANIC_INDEX + 16)
#define ITEM_SOOT_SACK		(LAST_BATTLE_MECHANIC_INDEX + 17)
#define ITEM_POKE_FLUTE		(LAST_BATTLE_MECHANIC_INDEX + 18)
#define ITEM_FAME_CHECKER	(LAST_BATTLE_MECHANIC_INDEX + 19)
#define ITEM_TEACHY_TV		(LAST_BATTLE_MECHANIC_INDEX + 20)

#define FIRST_MISC_KEY_INDEX	ITEM_BICYCLE
#define LAST_MISC_KEY_INDEX		ITEM_TEACHY_TV

// Story Key Items
#define ITEM_SS_TICKET		(LAST_MISC_KEY_INDEX + 1)
#define ITEM_EON_TICKET		(LAST_MISC_KEY_INDEX + 2)
#define ITEM_MYSTIC_TICKET	(LAST_MISC_KEY_INDEX + 3)
#define ITEM_AURORA_TICKET	(LAST_MISC_KEY_INDEX + 4)
#define ITEM_OLD_SEA_MAP	(LAST_MISC_KEY_INDEX + 5)
#define ITEM_LETTER			(LAST_MISC_KEY_INDEX + 6)
#define ITEM_DEVON_GOODS	(LAST_MISC_KEY_INDEX + 7)
#define ITEM_GO_GOGGLES		(LAST_MISC_KEY_INDEX + 8)
#define ITEM_DEVON_SCOPE	(LAST_MISC_KEY_INDEX + 9)
#define ITEM_BASEMENT_KEY	(LAST_MISC_KEY_INDEX + 10)
#define ITEM_SCANNER		(LAST_MISC_KEY_INDEX + 11)
#define ITEM_STORAGE_KEY	(LAST_MISC_KEY_INDEX + 12)
#define ITEM_ROOM_1_KEY		(LAST_MISC_KEY_INDEX + 13)
#define ITEM_ROOM_2_KEY		(LAST_MISC_KEY_INDEX + 14)
#define ITEM_ROOM_4_KEY		(LAST_MISC_KEY_INDEX + 15)
#define ITEM_ROOM_6_KEY		(LAST_MISC_KEY_INDEX + 16)
#define ITEM_METEORITE		(LAST_MISC_KEY_INDEX + 17)
#define ITEM_MAGMA_EMBLEM	(LAST_MISC_KEY_INDEX + 18)
#define ITEM_CONTEST_PASS	(LAST_MISC_KEY_INDEX + 19)
#define ITEM_OAKS_PARCEL	(LAST_MISC_KEY_INDEX + 20)
#define ITEM_SECRET_KEY		(LAST_MISC_KEY_INDEX + 21)
#define ITEM_BIKE_VOUCHER	(LAST_MISC_KEY_INDEX + 22)
#define ITEM_GOLD_TEETH		(LAST_MISC_KEY_INDEX + 23)
#define ITEM_CARD_KEY		(LAST_MISC_KEY_INDEX + 24)
#define ITEM_LIFT_KEY		(LAST_MISC_KEY_INDEX + 25)
#define ITEM_SILPH_SCOPE	(LAST_MISC_KEY_INDEX + 26)
#define ITEM_TRI_PASS		(LAST_MISC_KEY_INDEX + 27)
#define ITEM_RAINBOW_PASS	(LAST_MISC_KEY_INDEX + 28)
#define ITEM_TEA			(LAST_MISC_KEY_INDEX + 29)
#define ITEM_RUBY			(LAST_MISC_KEY_INDEX + 30)
#define ITEM_SAPPHIRE		(LAST_MISC_KEY_INDEX + 31)

#define FIRST_STORY_KEY_INDEX	ITEM_SS_TICKET
#define LAST_STORY_KEY_INDEX	ITEM_SAPPHIRE

#define ITEMS_COUNT	(LAST_STORY_KEY_INDEX + 1)	// 640

#define ITEM_TO_BERRY(itemId)	(((itemId - FIRST_BERRY_INDEX) + 1))
#define MAIL_NONE	0xFF

#define NUM_TECHNICAL_MACHINES	100
#define NUM_HIDDEN_MACHINES		8

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Check if the item is one that can be used on a Pokémon.
#define IS_POKEMON_ITEM(item) (\
((item) >= FIRST_MEDICINE_INDEX && (item) <= LAST_EV_FEATHER_INDEX) \
|| ((item) >= FIRST_CANDY_INDEX && (item) <= LAST_MED_FLUTE_INDEX) \
|| ((item) >= FIRST_X_ITEM_INDEX && (item) <= LAST_X_ITEM_INDEX) \
|| ((item) >= FIRST_EVO_ITEM_INDEX && (item) <= LAST_EVO_ITEM_INDEX) \
|| ((item) >= FIRST_BERRY_INDEX && (item) <= LAST_BERRY_INDEX) \
|| (item) == ITEM_DEEP_SEA_SCALE \
|| (item) == ITEM_DEEP_SEA_TOOTH \
|| (item) == ITEM_METAL_COAT \
|| (item) == ITEM_KINGS_ROCK \
|| (item) == ITEM_RAZOR_CLAW \
|| (item) == ITEM_RAZOR_FANG)

#endif  // GUARD_CONSTANTS_ITEMS_H
